/*
export enum BankName {
  HANKUK = [0, '한국은행'],
  KB = [1, '국민은행'],
  SC = [2, '제일은행'],
  CITY = [3, '한국시티은행'],
  HANA = [4, '하나은행'],
  SHINHAN = [5, '신한은행'],
  KBANK = [6, 'K-뱅크'],
  KAKAO = [7, '카카오'],
  TOSS = [8, '토스'],
  SUHYUP = [9, '수협은행'],
  BUSAN = [10, '부산은행'],
  KYUNGNAM = [11, '경남은행'],
  KYANGJOO = [12, '광주은행'],
  JUNBOK = [13, '전북은행'],
  JEJOO = [14, '제주은행'],
  LOTTE = [15, '롯데카드'],
  NONGHYUP = [16, '농협은행'],
  SAMSUNG = [17, '삼성카드'],
  HYUNDAI = [18, '현대카드'],
  WOORI = [19, '우리은행'],
  SINHYUP = [20, '신협은행'],
  SAEMAEULGEUMGO = [21, '새마을금고'],
  WOOCAEKUK = [22, '우체국'],
}*/